query GetDocumentVersion($objectKey: ID!, $runId: String!) {
  getDocumentVersion(objectKey: $objectKey, runId: $runId) {
    RunId
    ObjectKey
    CompletionTime
    QueuedTime
    WorkflowStartTime
    WorkflowExecutionArn
    ConfigVersion
    PageCount
    FileCount
    ManifestUri
    SummaryReportUri
    EvaluationReportUri
    Metering
    Sections {
      Id
      PageIds
      Class
      OutputJSONUri
      ConfidenceThresholdAlerts {
        attributeName
        confidence
        confidenceThreshold
      }
      ProcessingIssues {
        stage
        severity
        code
        message
        rootCause
      }
    }
    Pages {
      Id
      Class
      ImageUri
      TextUri
      OcrPageDataUri
    }
    Files {
      Key
      VersionId
      Size
    }
  }
}
